<a href="https://colab.research.google.com/github/LucjanSakowicz/data-science-bootcamp/blob/main/09_exercises/181_190_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pandas

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 181](#1)
* [Ćwiczenie 182](#2)
* [Ćwiczenie 183](#3)
* [Ćwiczenie 184](#4)
* [Ćwiczenie 185](#5)
* [Ćwiczenie 186](#6)
* [Ćwiczenie 187](#7)
* [Ćwiczenie 188](#8)
* [Ćwiczenie 189](#9)
* [Ćwiczenie 190](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

np.__version__

'1.22.4'

Uruchom poniższą instrukcję aby pobrać plik _insurance.csv_ do katalogu roboczego.

In [2]:
!wget -q https://storage.googleapis.com/esmartdata-courses-files/ml-course/insurance.csv

### <a name='1'></a> Ćwiczenie 181
Wczytaj plik _insurance.csv_ do obiektu DataFrame o nazwie _df_raw_ i wyświetl kilka początkowych wierszy.

In [5]:
df_raw = pd.read_csv('insurance.csv')
df_raw.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

Skopiuj obiekt _df_raw_ do zmiennej _df_ i wyświetl podstawowe informacje o obiekcie _df_.

In [6]:
df = df_raw.copy()

### <a name='2'></a> Ćwiczenie 182
Sprawdź czy istnieją zduplikowane wiersze w obiekcie _df_. Jeśli tak, wyświetl te wiersze.

In [10]:
df[df.duplicated()]

Empty DataFrame
Columns: [age, sex, bmi, children, smoker, region, charges]
Index: []

Usuń duplikaty w obiekcie _df_.

In [9]:
df = df.drop_duplicates()

### <a name='3'></a> Ćwiczenie 183
Wyświetl z obiektu _df_ zmienne z typem _object_.

__Wskazówka:__ Użyj metody _pd.DataFrame.select_dtypes()_

In [13]:
df.select_dtypes('object')

         sex smoker     region
0     female    yes  southwest
1       male     no  southeast
2       male     no  southeast
3       male     no  northwest
4       male     no  northwest
...      ...    ...        ...
1333    male     no  northwest
1334  female     no  northeast
1335  female     no  southeast
1336  female     no  southwest
1337  female    yes  northwest

[1337 rows x 3 columns]

Przekształć te zmienne do zmiennych kategorycznych.

__Wskazówka:__ Użyj metody _pd.DataFrame.astype()_.

In [48]:
df[['sex', 'smoker', 'region']] = df[['sex', 'smoker', 'region']].astype('category')
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1337 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1337 non-null   int64
 1   sex       1337 non-null   category
 2   bmi       1337 non-null   float64
 3   children  1337 non-null   int64
 4   smoker    1337 non-null   category
 5   region    1337 non-null   category
 6   charges   1337 non-null   float64
dtypes: category(3), float64(2), int64(2)
memory usage: 88.9 KB

Wyświetl z obiektu _df_ zmienne numeryczne (_float_, _int_).

__Wskazówka:__ Użyj metody _pd.DataFrame.select_dtypes()_

In [18]:
df.select_dtypes(('float', 'int'))

      age     bmi  children      charges
0      19  27.900         0  16884.92400
1      18  33.770         1   1725.55230
2      28  33.000         3   4449.46200
3      33  22.705         0  21984.47061
4      32  28.880         0   3866.85520
...   ...     ...       ...          ...
1333   50  30.970         3  10600.54830
1334   18  31.920         0   2205.98080
1335   18  36.850         0   1629.83350
1336   21  25.800         0   2007.94500
1337   61  29.070         0  29141.36030

[1337 rows x 4 columns]

Znajdź nazwy zmiennych numerycznych (_float_, _int_) z obiektu _df_.

In [20]:
list(df.select_dtypes(('float', 'int')).columns)

['age', 'bmi', 'children', 'charges']

### <a name='4'></a> Ćwiczenie 184

Wykonaj poniższe kroki:

* przypisz do zmiennej _df_cat_ zmienne kategoryczne z obiektu _df_ i utwórz ich kopię.

* przypisz do zmiennej _df_num_ zmienne numeryczne z obiektu _df_ i utwórz ich kopię.

In [21]:
df_cat = df.select_dtypes('category').copy()
df_num = df.select_dtypes(('float', 'int')).copy()

Wyświetl 5 pierwszych wierszy obiektu _df_cat_.

In [22]:
df_cat.head()

      sex smoker     region
0  female    yes  southwest
1    male     no  southeast
2    male     no  southeast
3    male     no  northwest
4    male     no  northwest

Wyświetl 5 pierwszych wierszy obiektu _df_num_.

In [23]:
df_num.head()

   age     bmi  children      charges
0   19  27.900         0  16884.92400
1   18  33.770         1   1725.55230
2   28  33.000         3   4449.46200
3   33  22.705         0  21984.47061
4   32  28.880         0   3866.85520

### <a name='5'></a> Ćwiczenie 185
Wyświetl podstawowe statystyki obiektu _df_cat_.

In [49]:
df_cat.describe()

         sex smoker     region
count   1337   1337       1337
unique     2      2          4
top     male     no  southeast
freq     675   1063        364

Wyświetl podstawowe statystyki obiektu _df_num_.

In [50]:
df_num.describe()

               age          bmi     children       charges
count  1337.000000  1337.000000  1337.000000   1337.000000
mean     39.222139    30.663452     1.095737  13279.121487
std      14.044333     6.100468     1.205571  12110.359656
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.290000     0.000000   4746.344000
50%      39.000000    30.400000     1.000000   9386.161300
75%      51.000000    34.700000     2.000000  16657.717450
max      64.000000    53.130000     5.000000  63770.428010

### <a name='6'></a> Ćwiczenie 186
Wyświetl podstawowe statystyki obiektu _df_ dla zmiennych numerycznych i dokonaj transponowania otrzymanego obiektu _DataFrame_.

In [30]:
df.select_dtypes(('float', 'int')).describe().T

,count,mean,std,min,25%,50%,75%,max
age,1337.0,39.222139,14.044333,18.0000,27.000,39.0000,51.00000,64.00000
bmi,1337.0,30.663452,6.100468,15.9600,26.290,30.4000,34.70000,53.13000
children,1337.0,1.095737,1.205571,0.0000,0.000,1.0000,2.00000,5.00000
charges,1337.0,13279.121487,12110.359656,1121.8739,4746.344,9386.1613,16657.71745,63770.42801

Wyświetl podstawowe statystyki obiektu _df_ dla zmiennych numerycznych, dokonaj transponowania otrzymanego obiektu _DataFrame_ i wytnij dwie columny _mean_ i _std_.

In [32]:
df.select_dtypes(('float', 'int')).describe().T[['mean', 'std']]

                  mean           std
age          39.222139     14.044333
bmi          30.663452      6.100468
children      1.095737      1.205571
charges   13279.121487  12110.359656

Wyświetl podstawowe statystyki obiektu _df_ dla zmiennych kategorycznych i dokonaj transponowania otrzymanego obiektu _DataFrame_.

In [33]:
df.select_dtypes(('category')).describe().T

       count unique        top  freq
sex     1337      2       male   675
smoker  1337      2         no  1063
region  1337      4  southeast   364

Sprawdź, czy są jakieś braki danych w obiekcie _df_.

In [34]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

### <a name='6'></a> Ćwiczenie 186
Wykorzystując bibliotekę _plotly express_ zbuduj histogram zmiennej _charges_.

Użyj funkcji _px.histogram()_ z następującymi parametrami: 
* width=800
* height=400
* nbins=50
* facet_col='smoker'
* facet_row='sex'

In [38]:
px.histogram(df, x='charges', width=800, height=400, nbins=50, facet_col='smoker', facet_row='sex')

Wykorzystując bibliotekę _plotly express_ znajdź rozkład zmiennej _smoker_.

Użyj funkcji _px.histogram()_ z następującymi parametrami: 
* width=800
* height=400
* facet_col='sex'
* color='sex'

In [39]:
px.histogram(df, x='smoker', width=800, height=400, facet_col='sex', color='sex')

### <a name='7'></a> Ćwiczenie 187
Skonwertuj zmienne kategoryczne obietku _df_ do kodowania 0-1 i przypisz do zmiennej _df_dummies_.

__Wskazówka:__ Użyj funkcji _pd.get_dummies()_ z parametrem _drop_first=True_.

In [51]:
df_dummies = pd.get_dummies(df, drop_first=True)
df_dummies.head()

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,0,1,0,0,1
1,18,33.770,1,1725.55230,1,0,0,1,0
2,28,33.000,3,4449.46200,1,0,0,1,0
3,33,22.705,0,21984.47061,1,0,1,0,0
4,32,28.880,0,3866.85520,1,0,1,0,0

### <a name='8'></a> Ćwiczenie 188
Wyznacz korelacje zmiennych w obiekcie _df_dummies_ i przypisz do zmiennej _corr_.

In [52]:
corr = df_dummies.corr()
corr

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
age,1.000000,0.109344,0.041536,0.298308,-0.019814,-0.025587,0.001495,-0.012311,0.009415
bmi,0.109344,1.000000,0.012755,0.198401,0.046397,0.003746,-0.136138,0.270057,-0.006211
children,0.041536,0.012755,1.000000,0.067389,0.017848,0.007331,0.026044,-0.023492,0.021538
charges,0.298308,0.198401,0.067389,1.000000,0.058044,0.787234,-0.038695,0.073578,-0.043637
sex_male,-0.019814,0.046397,0.017848,0.058044,1.000000,0.076596,-0.012482,0.017578,-0.003767
smoker_yes,-0.025587,0.003746,0.007331,0.787234,0.076596,1.000000,-0.036321,0.068282,-0.037168
region_northwest,0.001495,-0.136138,0.026044,-0.038695,-0.012482,-0.036321,1.000000,-0.345909,-0.320493
region_southeast,-0.012311,0.270057,-0.023492,0.073578,0.017578,0.068282,-0.345909,1.000000,-0.346614
region_southwest,0.009415,-0.006211,0.021538,-0.043637,-0.003767,-0.037168,-0.320493,-0.346614,1.000000

Wytnij kolumnę z obiektu _corr_ dla zmiennej _charges_ (jako obiekt DataFrame) i posortuj wartości malejąco.

In [58]:
charges = corr[['charges']].sort_values(by='charges', ascending=False)
charges

                   charges
charges           1.000000
smoker_yes        0.787234
age               0.298308
bmi               0.198401
region_southeast  0.073578
children          0.067389
sex_male          0.058044
region_northwest -0.038695
region_southwest -0.043637

Wykorzystując bibliotekę _plotly express_ utwórz wykres słupkowy dla tak posortowanych wartości. Pomiń pierwszy element obiektu.

In [61]:
tmp = charges.reset_index()[1:]
tmp.columns = ['variable', 'value']
px.bar(tmp, x='variable', y='value', width=900)

### <a name='9'></a> Ćwiczenie 189
Skopiuj obiekt _df_dummies_ do zmiennej _data_. Następnie wyrwij z tego obiektu kolumnę _charges_ i przypisz do zmiennej _target_.

In [62]:
data = df_dummies.copy()
target = data.pop('charges')

Wyświetl 5 pierwszych wierszy obiektu _data_. Upewnij się, że nie ma w nim kolumny _charges_.

In [63]:
data.head()

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,0,1,0,0,1
1,18,33.770,1,1,0,0,1,0
2,28,33.000,3,1,0,0,1,0
3,33,22.705,0,1,0,1,0,0
4,32,28.880,0,1,0,1,0,0

Wyświetl 5 pierwszych wierszy obiektu _target_.

In [64]:
target.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

### <a name='10'></a> Ćwiczenie 190
Wykorzystując bibliotekę _scikit-learn_ oraz funkcję _train_test_split_ podziel dane z obiektów _data_ i _target_ na zbiór treningowy (_X\_train_, _y\_train_) oraz zbiór testowy (_X\_test_, _y\_test_). Do zbioru testowego przydziel 20% próbek. 

Wyświetl rozmiar obiektów:
* _X\_train_
* _X\_test_
* _y\_train_
* _y\_test_

In [65]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2)

print(f'X_train shape: {X_train.shape}')
print(f'X_test shape: {X_test.shape}')
print(f'y_train shape: {y_train.shape}')
print(f'y_test shape: {y_test.shape}')

X_train shape: (1069, 8)
X_test shape: (268, 8)
y_train shape: (1069,)
y_test shape: (268,)

Zapisz obiekty:
* _X\_train_
* _X\_test_
* _y\_train_
* _y\_test_  

do plików csv odpowiednio o nazwie:
* X_train.csv
* X_test.csv
* y_train.csv
* y_test.csv

In [68]:
X_train.to_csv('X_train.csv')
X_test.to_csv('X_test.csv')
y_train.to_csv('y_train.csv')
y_test.to_csv('y_test.csv')

Uruchom poniższą komórkę w celu sprawdzenia.

In [69]:
!head -5 X_test.csv
!head -5 X_train.csv
!head -5 y_train.csv
!head -5 y_test.csv

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
648,18,28.5,0,1,0,0,0,0
362,19,21.7,0,0,1,0,0,1
669,40,29.81,1,0,0,0,1,0
236,18,26.73,0,0,0,0,1,0
,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
100,41,31.6,0,0,0,0,0,1
565,19,30.495,0,0,0,1,0,0
480,63,41.325,3,1,0,1,0,0
1327,51,30.03,1,1,0,0,1,0
,charges
100,6186.127
565,2128.43105
480,15555.18875
1327,9377.9047
,charges
648,1712.227
362,13844.506
669,6500.2359
236,1615.7667